`r if (knitr:::is_html_output()) '# References {-}'`

## Texts for Your Shelf


The following are three texts I have recommended in the past to folks who are interested in doing Bayesian data analysis. They can be seen as introduction, intermediate, and advanced respectively.

Kruschke, J. (2014) *Doing Bayesian Data Analysis*. A very introductory text, but might be good for those not too confident in statistics generally speaking. And who doesn't like puppies? 2nd Edition.

McElreath, R. (2020). *Statistical Rethinking*.  A great modeling book in general, by one who has contributed a lot to helping others learn Stan and Bayesian analysis. 2nd Edition.

Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., and Rubin, D. B. (2013). *Bayesian Data Analysis*. 3rd Edition.


## Stan Specific Resources

[Main website](http://mc-stan.org/)

[Stan Users Group](http://discourse.mc-stan.org/)

[Stan Best Practices](https://github.com/stan-dev/stan/wiki/Stan-Best-Practices)

[Example Models](https://github.com/stan-dev/example-models)


More resources [here](https://mc-stan.org/users/documentation/)


<!-- ## Other -->

<!-- Statisticat, LLC. [*Bayesian Inference*](https://cran.r-project.org/web/packages/LaplacesDemon/vignettes/BayesianInference.pdf). A quick overview from the original author of the <span class="pack">LaplacesDemon</span> package. -->


## Works Cited/Used
